#pv-loki.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-loki-0
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "hostpath"
  claimRef:
    namespace: observability
    name: storage-loki-0
  hostPath:
    path: "/mnt/host/d/k8s_shared/loki"
    type: DirectoryOrCreate